### ISSUE TITLE
Check images from Mattermost / Gitea / Discourse + check deriviation of keys

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/tf-images#72]
The Jimber team will check the implementations of Mattermost / Gitea and Discourse for the SSO/TF-Connect implementation. Implementation must be secure and fluent (no errors / check on email validity / good feedback to users). Furthermore we will check if we can use derivation keys from the TF-Connect app as SSH and PGP keys in gitea.

**Comment by JonasWijne** [comment]
## Analysis **Gitea**: 
- [x] Implementation is working
- [x] Login with threefold connect works
- [x] Signature is checked based on the Threefold backend
- [x] Email is mandatory but is not yet checked with openkyc => **this will need to happen because in theory this could be a problem**
- [x] Email is only set once so when you change your email this could give a problem later => **needs to be fixed**
- [x] Code review
*****
## Todo
- [ ] QA integration + login + user rights
- [ ] Deriviate SSL keys
- [ ] add kyc check for email with openkyc


## Running on
https://gitea.staging.jimber.io/

**Comment by jdelrue** [comment]
## Analysis **Mattermost**: 
Works:
- [x] Implementation is working
- [x] Login with threefold connect works
- [x] Check websockets not working

##  Todo

- [ ] Check if email is checked
- [ ] Check if email is checked with openkyc 
- [ ] remove .3bot  from username
- [ ] QA on login flows


## Running on 
https://mattermost.staging.jimber.io/

**Comment by ldruwel** [comment]
## Analysis **Discourse**: 
Works:
- [x] Implementation is working
- [ ] Login with threefold connect works
- [ ] Check websockets not working

##  Todo

- [x] Check if email is checked
- [x] Check if email is checked with openkyc 
- [ ] remove .3bot  from username
- [ ] QA on login flows

## Remarks
- Documentation point to origin fork
- Build fixed by Delrue
- Mail server not working atm


## Running on 
https://discourse.staging.jimber.io

**Comment by JonasWijne** [comment]
### Analysis sozu for proxy

- [x] build 
- [x] setup with test service
- [x] setup with gitea & mattermost
- [x] basic documentation 
- [x] https 
- [ ] https documentation

**Comment by JonasWijne** [comment]
![image](https://user-images.githubusercontent.com/6184820/153073198-0e68e9d9-daf7-42c3-bd5e-790502326a67.png)
sozu with backend

**Comment by JonasWijne** [comment]
https works but we'll have to build with openssl feature 
documentation is still needed
